version: '2'

services:

  mapserver:
    image: camptocamp/mapserver:latest
    links:
      - db
    volumes:
      - ./sos.map:/etc/mapserver/mapserver.map


  db:
    image: camptocamp/postgres:9.6
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_USER: www-data
      POSTGRES_PASSWORD: www-data
      POSTGRES_DB: sos
    command: postgres -c log_statement=all
    ports:
      - 15432:5432


  web:
    image: nginx
    ports:
      - "8080:80"
    links:
      - mapserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
